name: Remove exp branch
on:
  pull_request:
    types: [closed]
permissions:
  contents: write
jobs:
  get_name:
    if: github.event.pull_request.merged == true
    name: Delete exp branch
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          #   fetch-depth: "0"
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Git user setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Extract branch name
        id: extract_name
        run: echo "BRANCH_NAME=`echo ${GITHUB_HEAD_REF#refs/heads/} | sed 's/issue\//exp\//g'`" >> $GITHUB_OUTPUT
      - name: Remove branch
        run: git push origin -d "${{steps.extract_name.outputs.BRANCH_NAME}}"

        # skontrolovat z ktorej branche je PR spraveny
