name: Remove exp branch
on:
  pull_request:
permissions:
  pull-requests: write
jobs:
  build:
    name: Check branches
    runs-on: ubuntu-latest
    steps:
      - run: git branch -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
